"""DOA input dimensions and initial 3D simulation convention constants."""

ARRAY_COUNT = 3
MICROPHONES_PER_ARRAY = 8
SAMPLE_RATE_HZ = 48_000
SAMPLE_DURATION_SECONDS = 1
SAMPLE_COUNT = SAMPLE_RATE_HZ * SAMPLE_DURATION_SECONDS

ARRAY_SAMPLE_SHAPE = (MICROPHONES_PER_ARRAY, SAMPLE_COUNT)
SYSTEM_SAMPLE_SHAPE = (ARRAY_COUNT, MICROPHONES_PER_ARRAY, SAMPLE_COUNT)

# Initial three-dimensional simulation assumptions; these are not hardware facts.
WORLD_DIMENSIONS = 3
AZIMUTH_MIN_DEGREES = 0.0
AZIMUTH_MAX_DEGREES_EXCLUSIVE = 360.0
ELEVATION_MIN_DEGREES = -90.0
ELEVATION_MAX_DEGREES = 90.0
MUSIC_AZIMUTH_SCAN_STEP_DEGREES = 1.0
MUSIC_ELEVATION_SCAN_STEP_DEGREES = 1.0
DEFAULT_ARRAY_LAYER_HALF_WIDTH_METERS = 0.045
DEFAULT_ARRAY_LAYER_SPACING_METERS = 0.045
DEFAULT_UPPER_LAYER_ROTATION_DEGREES = 45.0
SPEED_OF_SOUND_METERS_PER_SECOND = 343.0
FREQUENCY_DOMAIN_TRANSFORM = "FFT/STFT"
INITIAL_NARROWBAND_VALIDATION = True
DEFAULT_TEST_TONE_FREQUENCY_HZ = 1_000.0
QUALITY_SCORE_MIN = 0.0
QUALITY_SCORE_MAX = 1.0
MUSIC_MIN_SNAPSHOT_NORM = 1.0e-9
MUSIC_VALID_QUALITY_THRESHOLD = 0.05

# Simulation-only default localization layout; not verified hardware geometry.
DEFAULT_LOCALIZATION_ARRAY_IDS = ("array-0", "array-1", "array-2")
DEFAULT_LOCALIZATION_ARRAY_POSITIONS_METERS = (
    (0.0, 0.0, 0.0),
    (4.0, 0.0, 0.0),
    (2.0, 3.4641016151, 0.0),
)
LOCALIZATION_MIN_USABLE_RAYS = 2
LOCALIZATION_CONDITION_LIMIT = 1.0e10
LOCALIZATION_PARALLEL_DOT_THRESHOLD = 0.999
